global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'miu'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 10s

  - job_name: 'lavalink'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['lavalink:2333']
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s 